custom_http_response-header

diff --git a/0x0F-load_balancer/0-custom_http_response-header b/0x0F-load_balancer/0-custom_http_response-header
--- a/0x0F-load_balancer/0-custom_http_response-header
+++ b/0x0F-load_balancer/0-custom_http_response-header
@@ -1,18 +1,84 @@
 #!/usr/bin/env bash
-# Script that configures Nginx server with a custom header
-sudo apt-get -y update
-sudo apt-get -y install nginx
-sudo sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/default
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
+
+# uncomment to see the script run in action
+#set -x
+
+echo -e "Updating and doing some minor checks...\n"
+
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
-sudo mkdir -p /var/www/html
-sudo chmod -R 755 /var/www
-echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
-file=/etc/nginx/sites-enabled/default
-redirect="\     rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/$1";
-sudo sed -i " /server_name _;/a ${redirect} permanent;" $file
-echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
-err="\        error_page\ 404 /custom_404.html;\n\        location\ = \ /custom_404.html\  {\n\t\troot\ /usr/share/nginx/html;\n\t\tinternal;\n\t}"
-sudo sed -i "/server_name _;/a ${err}" $file
-custom_header="\    add_header X-Served-By $HOSTNAME;"
-sudo sed -i "/server_name _;/a ${custom_header}" $file
-sudo service nginx restart
+
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
